name: "Update website from main"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Pull your workflow repo (GitHub checkout)
      - name: Pull from main
        uses: actions/checkout@v4

      # Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Update droplet repository
      - name: Git pull on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes root@${{ secrets.SSH_HOST }} \
          "cd /root/COP4331_MERN_Project && git fetch --all && git reset --hard origin/main && \
           if [ -f package.json ]; then npm install && npm run build; else echo 'No build, skipping'; fi"
